### ISSUE TITLE
[BUG] Changing download folder doesn't appear to work (again)

### ISSUE THREAD

**Issue by egcp** [neffo/bing-wallpaper-gnome-extension#106]
Hi, The extension is great. However for the Gnome 40 version, the Download Folder option is not working. The user cannot choose a different folder to store the wallpapers. The option is there, and when clicked it opens a file manager to choose a different folder, but the selection is never applied. Therefore, the folder is always ~/BingWallpaper/. It worked fine for previous Gnome versions. This seems to be reported in relation to an old issue (#44). Thanks!

**Comment by neffo** [comment]
Thanks for the report, I've got a fix in a branch atm. This branch still needs a bit more testing, but hoping to publish it soon.

**Comment by neffo** [comment]
Should be fixed in #102 v33

**Comment by ikswokor** [comment]
Still not working. When i choose new folder (existing or create new one) and close settings window, when I reopen it, the download folder goes back to the state it was in before the change (even if I deleted it).

**Comment by neffo** [comment]
@ikswokor which GNOME version and distro?

when you click the open folder button where does it go?

**Comment by ikswokor** [comment]
this is how it looks https://youtu.be/eaY8-TEHTe0

OS - Arch Linux x86_64
kernel - 5.12.8-arch1-1 
gnome version - 40.1.0
wayland -  1.19.0-1

**Comment by neffo** [comment]
Yep, last minute change broke it undoing the fix. Thanks for the report, if you are running git you can test the v34 branch for a fix.

**Comment by ikswokor** [comment]
Yup, in branch v34 everything works great. Thanks a lot :)

**Comment by egcp** [comment]
Thanks!  Version 34 works as expected.

**Comment by neffo** [comment]
Reopened as this doesn't seem to be working again
