### ISSUE TITLE
Causing a Glitch traced back to this Extension

### ISSUE THREAD

**Issue by duke-silver** [neffo/bing-wallpaper-gnome-extension#17]
I am experiencing a sort of glitch where every minute (on the nose) my desktop freezes up momentarily (a couple of seconds), any open windows get about 20 pixels smaller on each side and a square border fills that space. Then the screen flashes (transitions) to the login screen background (just the background, no login form or top panel widgets) and then back immediately.

Turn extensions off, symptoms stop. turn this one extension one, they start again. turn all my other extensions on but not this one, no symptoms. I have just upgraded the extension (v14) moments ago hoping it would contain a fix. no dice - still producing same issue.

Ubuntu Gnome 17.04 (upgraded from 16.10)
Gnome 3.24.2

**Comment by neffo** [comment]
Hmm, that sounds like a shell restart. It's caught in a loop by the sounds of it.

To help me replicate it can you post a screenshot of your settings?

And can you turn on debug logging with this command:
`gsettings --schemadir ~/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/schemas set org.gnome.shell.extensions.bingwallpaper debug-logging true`

And then `journalctl -e`, that will open the journal and skip to the end. There will be a line (I presume) that says:
`org.gnome.Shell.desktop[2543]: BingWallpaper extension: next check in 60 seconds @ local time 2017-09-14 00:10:49`
You'll want to look for events around 60 seconds after that line, it could be a gnome-shell event or a JS error or JS warning. If you don't know what to look for, you could just paste the whole log from that point until the first line like this: `gnome-shell[2543]: GNOME Shell started at Thu Sep 14 2017 00:09:49 GMT+1000 (AEST)`

(That'll be when GNOME has finished restarting.)

**Comment by neffo** [comment]
I haven't yet been able to replicate this bug, there may be a quirk in the handling of one of the settings or something specific with your GNOME configuration. I am also running Ubuntu 17.04.

**Comment by marco897** [comment]
I'm experiencing the same glitch, on Fedora 27. `journalctl -e` shows:

```
Jan 11 11:34:08 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: next check in 86400 seconds @ local time 2018-01-12 11:34:08
Jan 11 11:34:08 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: market: de-DE
Jan 11 11:34:08 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: fetching: https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mbl=1&mkt=de-DE
Jan 11 11:34:08 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: Recieved 914 bytes
Jan 11 11:34:08 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: auto resolution selected (1920x1200)
Jan 11 11:34:08 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: Image already downloaded
Jan 11 11:34:08 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: Next refresh due @ 2018-01-11 23:00 +0000 = 44751.030463 seconds from now (2018-01-11 10:34 +0000)
Jan 11 11:34:08 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: next check in 45051.030463 seconds @ local time 2018-01-12 00:05:00
Jan 11 11:34:09 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:09 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:09 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:09 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-11 11:35:09
Jan 11 11:34:09 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 11 11:34:09 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: highest res: 1920 x 1200
Jan 11 11:34:09 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: detected best resolution 1920x1200
Jan 11 11:34:09 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:10 schroedinger gnome-shell[2542]: loading default theme (Adwaita)
Jan 11 11:34:12 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:12 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:12 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:12 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-11 11:35:12
Jan 11 11:34:12 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 11 11:34:12 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: highest res: 1920 x 1200
Jan 11 11:34:12 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: detected best resolution 1920x1200
Jan 11 11:34:12 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:13 schroedinger gnome-shell[2542]: loading default theme (Adwaita)
Jan 11 11:34:16 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:16 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:16 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:16 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-11 11:35:16
Jan 11 11:34:16 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 11 11:34:16 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: highest res: 1920 x 1200
Jan 11 11:34:16 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: detected best resolution 1920x1200
Jan 11 11:34:16 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:17 schroedinger gnome-shell[2542]: loading default theme (Adwaita)
Jan 11 11:34:19 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:19 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:19 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:19 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-11 11:35:19
Jan 11 11:34:19 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 11 11:34:19 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: highest res: 1920 x 1200
Jan 11 11:34:19 schroedinger org.gnome.Shell.desktop[2542]: BingWallpaper extension: detected best resolution 1920x1200
Jan 11 11:34:19 schroedinger gnome-software[2956]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 11:34:20 schroedinger gnome-shell[2542]: loading default theme (Adwaita)
```

Then it happens again starting at 11:35:19.

**Comment by neffo** [comment]
Yeah, sorry about this bug. It's been a real pain to nail down...

Can you set full debug logging on with this command:
`dconf write /org/gnome/shell/extensions/bingwallpaper/debug-logging true`

And show me the journal again?

**Comment by neffo** [comment]
This is what I see when debug logging is on (NOTE: I will test this in a Fedora 27 VM also):
`Jan 11 22:04:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-11 22:05:28
Jan 11 22:04:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 11 22:04:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: highest res: 1920 x 1200
Jan 11 22:04:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: detected best resolution 1920x1200
Jan 11 22:04:28 ubuntupc gnome-software[18481]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 22:05:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: next check in 86400 seconds @ local time 2018-01-12 22:05:28
Jan 11 22:05:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: market: en-AU
Jan 11 22:05:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: fetching: https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mbl=1&mkt=en-AU
Jan 11 22:05:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: Recieved 861 bytes
Jan 11 22:05:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: auto resolution selected (1920x1200)
Jan 11 22:05:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: Downloading https://bing.com/az/hprichbg/rb/BowSnow_EN-AU9208049425_1920x1080.jpg to file:///home/michael/Pictures/BingWallpaper/20180110-BowSnow_EN-AU9208049425_1920x1080.jpg
Jan 11 22:05:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: Next refresh due @ 2018-01-11 13:00 +0000 = 3271.344105 seconds from now (2018-01-11 12:05 +0000)
Jan 11 22:05:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: next check in 3571.344105 seconds @ local time 2018-01-11 23:05:00
Jan 11 22:05:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: got_headers
Jan 11 22:05:28 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: got_headers
Jan 11 22:05:28 ubuntupc gnome-shell[18312]: JS WARNING: [/home/michael/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js 372]: Too many arguments to method Gio.OutputStream.write: expected 2, got 3
(repeated lots)
^ NOTE: this is a bug

Jan 11 22:05:29 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: Download successful
Jan 11 22:05:29 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: Raw: /home/michael/Pictures/BingWallpaper/20171221-RosehipRobin_EN-AU10765383343_1920x1080.jpg,/home/michael/Pictures/BingWallpaper/20171222-SFSantaCon_EN-AU11072721713_1920x1080.jpg,/home/m
Jan 11 22:05:29 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: Settings: delete:no max: 7
Jan 11 22:05:29 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: image: /home/michael/Pictures/BingWallpaper/20171221-RosehipRobin_EN-AU10765383343_1920x1080.jpg <snip>
Jan 11 22:05:29 ubuntupc org.gnome.Shell.desktop[18312]: BingWallpaper extension: wrote back this: /home/michael/Pictures/BingWallpaper/20171222-SFSantaCon_EN-AU11072721713_1920x1080.jpg <snip>

`

**Comment by marco897** [comment]
I don't see any additional information with:
`dconf write /org/gnome/shell/extensions/bingwallpaper/debug-logging true`
I think that I have debugging already activated since I used `gsettings --schemadir ~/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/schemas set org.gnome.shell.extensions.bingwallpaper debug-logging true` from your first comment.

```
Jan 11 13:58:47 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: next check in 86400 seconds @ local time 2018-01-12 13:58:47
Jan 11 13:58:47 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: market: de-DE
Jan 11 13:58:47 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: fetching: https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mbl=1&mkt=de-DE
Jan 11 13:58:47 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: Recieved 914 bytes
Jan 11 13:58:47 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: auto resolution selected (1920x1200)
Jan 11 13:58:47 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: Image already downloaded
Jan 11 13:58:47 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: Next refresh due @ 2018-01-11 23:00 +0000 = 36072.02779 seconds from now (2018-01-11 12:58 +0000)
Jan 11 13:58:47 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: next check in 36372.02779 seconds @ local time 2018-01-12 00:05:00
Jan 11 13:58:47 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:47 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:47 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:48 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-11 13:59:48
Jan 11 13:58:48 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 11 13:58:48 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: highest res: 1920 x 1200
Jan 11 13:58:48 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: detected best resolution 1920x1200
Jan 11 13:58:48 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:48 schroedinger gnome-shell[22385]: loading default theme (Adwaita)
Jan 11 13:58:49 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:49 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:49 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:49 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-11 13:59:49
Jan 11 13:58:49 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 11 13:58:49 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: highest res: 1920 x 1200
Jan 11 13:58:49 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: detected best resolution 1920x1200
Jan 11 13:58:49 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:50 schroedinger gnome-shell[22385]: loading default theme (Adwaita)
Jan 11 13:58:52 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:52 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:52 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:52 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-11 13:59:52
Jan 11 13:58:52 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 11 13:58:52 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: highest res: 1920 x 1200
Jan 11 13:58:52 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: detected best resolution 1920x1200
Jan 11 13:58:52 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:53 schroedinger gnome-shell[22385]: loading default theme (Adwaita)
Jan 11 13:58:54 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:54 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:54 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:54 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-11 13:59:54
Jan 11 13:58:54 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 11 13:58:54 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: highest res: 1920 x 1200
Jan 11 13:58:54 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: detected best resolution 1920x1200
Jan 11 13:58:54 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:55 schroedinger gnome-shell[22385]: loading default theme (Adwaita)
```

**Comment by neffo** [comment]
That this line is repeated is a concern:
```Jan 11 13:58:49 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:49 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 11 13:58:49 schroedinger gnome-software[22804]: no app for changed BingWallpaper@ineffable-gmail.com
```

I wonder if you have multiple copies of the extension running?

Can you check this with this command?
```dconf read /org/gnome/shell/enabled-extensions```

**Comment by marco897** [comment]
`['background-logo@fedorahosted.org', 'BingWallpaper@ineffable-gmail.com']`

**Comment by neffo** [comment]
I'll dig into it further! Bare with me.

**Comment by neffo** [comment]
Ok, I wasn't able to replicate this in Fedora 27 in a VM, however the repeated lines seems to me to indicate that the extension is being run multiple times (or that the enable() function is being called more than once).

Can you try this for me?

1) Press Alt-F2
2) Type "lg"
3) Click "Extensions" in the top right of the window that drops down
4) Count the instances of "Bing Wallpaper Changer" in that list - should only be one

Thanks so much for helping me debug it!

**Comment by marco897** [comment]
Hi, I see only one instance on the list.

I just reactivated the extension. The first time it ran, actually downloading a new picture, I got a different error message:
```
Jan 12 10:15:03 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: next check in 86400 seconds @ local time 2018-01-13 10:15:03
Jan 12 10:15:03 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: market: de-DE
Jan 12 10:15:03 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: fetching: https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mbl=1&mkt=de-DE
Jan 12 10:15:03 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: Recieved 905 bytes
Jan 12 10:15:03 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: auto resolution selected (1920x1200)
Jan 12 10:15:03 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: Downloading https://bing.com/az/hprichbg/rb/TreasuryCandles_DE-DE9414027460_1920x1080.jpg to file:///home/marcoce/Pictures/BingWallpaper/20180111-TreasuryCandles_DE-DE9414027460_1920x1080.jpg
Jan 12 10:15:03 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: Next refresh due @ 2018-01-12 23:00 +0000 = 49496.060388 seconds from now (2018-01-12 09:15 +0000)
Jan 12 10:15:03 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: next check in 49796.060388 seconds @ local time 2018-01-13 00:05:00
Jan 12 10:15:03 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: got_headers
Jan 12 10:15:03 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: got_headers
Jan 12 10:15:03 schroedinger gnome-shell[22385]: JS WARNING: [/home/marcoce/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js 372]: Too many arguments to method Gio.OutputStream.write: expected 2, got 3
Jan 12 10:15:03 schroedinger gnome-shell[22385]: JS WARNING: [/home/marcoce/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js 372]: Too many arguments to method Gio.OutputStream.write: expected 2, got 3
Jan 12 10:15:03 schroedinger gnome-shell[22385]: JS WARNING: [/home/marcoce/.local/share/gnome-shell/extensions/BingWallpaper@ineffable-gmail.com/extension.js 372]: Too many arguments to method Gio.OutputStream.write: expected 2, got 3
```
with the last line repeating many time. Then, it runs again multiple times without this JS WARNING.

**Comment by neffo** [comment]
Yeah, that's just a warning you can ignore those lines. (I need to fix that, but it won't cause any problems.)

Do you see any other repeated lines?

Like this one:
```
Jan 11 13:58:49 schroedinger org.gnome.Shell.desktop[22385]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-11 13:59:49
```
only a few seconds apart?

**Comment by neffo** [comment]
Ok I've just pushed a commit that will hopefully fix the (wierd) intermittent bug people are seeing.

**Comment by marco897** [comment]
Hi, now it is solved on my machine. Thanks!
I am not sure that the new version alone is what solved it. I first tried to overwrite the version from extensions.gnome.org with the git version and it did not solve the problem. Instead, manually adding it to ` /org/gnome/shell/enabled-extensions` in `dconf`, and logout and login, seems to work.
I'll check again when the updated version is available on extensions.gnome.org.

**Comment by marco897** [comment]
Bad news... I just tried to disable and re-enable it in `gnome-tweak-tools`. It triggered the bug again, slightly different this time:
```
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: next check in 86400 seconds @ local time 2018-01-16 11:32:44
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: market: de-DE
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: fetching: https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mbl=1&mkt=de-DE
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: Recieved 937 bytes
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: auto resolution selected (1920x1200)
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: XDG pictures directory detected as /home/marcoce/Pictures saving pictures to /home/marcoce/Pictures/BingWallpaper/
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: Image already downloaded
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: Next refresh due @ 2018-01-15 23:00 +0000 = 44835.057402 seconds from now (2018-01-15 10:32 +0000)
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: next check in 45135.057402 seconds @ local time 2018-01-16 00:05:00
Jan 15 11:32:44 schroedinger gnome-software[8962]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 11:32:44 schroedinger gnome-software[8962]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 11:32:44 schroedinger gnome-software[8962]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 11:32:44 schroedinger gnome-software[8962]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 11:32:44 schroedinger gnome-software[8962]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: WARNING: init() called more than once, ignoring
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: enable() called
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-15 11:33:44
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: highest res: 1920 x 1200
Jan 15 11:32:44 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: detected best resolution 1920x1200
Jan 15 11:32:44 schroedinger gnome-software[8962]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 11:32:46 schroedinger gnome-software[8962]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 11:32:46 schroedinger gnome-software[8962]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 11:32:46 schroedinger gnome-software[8962]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 11:32:46 schroedinger gnome-software[8962]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 11:32:46 schroedinger gnome-software[8962]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 11:32:46 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: WARNING: init() called more than once, ignoring
Jan 15 11:32:46 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: enable() called
Jan 15 11:32:46 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-15 11:33:46
Jan 15 11:32:46 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 15 11:32:46 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: highest res: 1920 x 1200
Jan 15 11:32:46 schroedinger org.gnome.Shell.desktop[8382]: BingWallpaper extension: detected best resolution 1920x1200
Jan 15 11:32:46 schroedinger gnome-software[8962]: no app for changed BingWallpaper@ineffable-gmail.com
```

**Comment by neffo** [comment]
@marco897 thanks so much for helping me debug this one, I really appreciate it!

I've just pushed another commit which I think will work better, let me know if that works

**Comment by marco897** [comment]
No, I am sorry, the bug is still there.
If it is useful, note that the first time it is enabled, it runs only once and it set the next check timer to 60 seconds:
```
Jan 15 14:21:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: enable() called
Jan 15 14:21:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-15 14:22:09
Jan 15 14:21:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 15 14:21:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: highest res: 1920 x 1200
Jan 15 14:21:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: detected best resolution 1920x1200
Jan 15 14:21:09 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
```
but after the first 60 seconds, it runs many times in a few seconds, during which everything is completely frozen:
```
Jan 15 14:22:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: next check in 86400 seconds @ local time 2018-01-16 14:22:09
Jan 15 14:22:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: market: de-DE
Jan 15 14:22:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: fetching: https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mbl=1&mkt=de-DE
Jan 15 14:22:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: Recieved 937 bytes
Jan 15 14:22:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: auto resolution selected (1920x1200)
Jan 15 14:22:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: XDG pictures directory detected as /home/marcoce/Pictures saving pictures to /home/marcoce/Pictures/BingWallpaper/
Jan 15 14:22:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: Image already downloaded
Jan 15 14:22:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: Next refresh due @ 2018-01-15 23:00 +0000 = 34670.042833 seconds from now (2018-01-15 13:22 +0000)
Jan 15 14:22:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: next check in 34970.042833 seconds @ local time 2018-01-16 00:05:00
Jan 15 14:22:09 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:09 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: WARNING: init() called more than once, ignoring
Jan 15 14:22:09 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: enable() called
Jan 15 14:22:09 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:09 schroedinger gnome-software[13211]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 14:22:09 schroedinger gnome-software[13211]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 14:22:10 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-15 14:23:10
Jan 15 14:22:10 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 15 14:22:10 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: highest res: 1920 x 1200
Jan 15 14:22:10 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: detected best resolution 1920x1200
Jan 15 14:22:10 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:10 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:10 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:10 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:10 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: WARNING: init() called more than once, ignoring
Jan 15 14:22:10 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: enable() called
Jan 15 14:22:10 schroedinger gnome-software[13211]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 14:22:10 schroedinger gnome-software[13211]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 14:22:10 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-15 14:23:10
Jan 15 14:22:10 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 15 14:22:10 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: highest res: 1920 x 1200
Jan 15 14:22:10 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: detected best resolution 1920x1200
Jan 15 14:22:10 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:11 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:11 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:11 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:11 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: WARNING: init() called more than once, ignoring
Jan 15 14:22:11 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: enable() called
Jan 15 14:22:11 schroedinger gnome-software[13211]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 14:22:11 schroedinger gnome-software[13211]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 14:22:11 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-15 14:23:11
Jan 15 14:22:11 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 15 14:22:11 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: highest res: 1920 x 1200
Jan 15 14:22:11 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: detected best resolution 1920x1200
Jan 15 14:22:11 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:12 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:12 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: WARNING: init() called more than once, ignoring
Jan 15 14:22:12 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: enable() called
Jan 15 14:22:12 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:12 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:12 schroedinger gnome-software[13211]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 14:22:12 schroedinger gnome-software[13211]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 14:22:12 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-15 14:23:12
Jan 15 14:22:12 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 15 14:22:12 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: highest res: 1920 x 1200
Jan 15 14:22:12 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: detected best resolution 1920x1200
Jan 15 14:22:12 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:13 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:13 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:13 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
Jan 15 14:22:13 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: WARNING: init() called more than once, ignoring
Jan 15 14:22:13 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: enable() called
Jan 15 14:22:13 schroedinger gnome-software[13211]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 14:22:13 schroedinger gnome-software[13211]: no app for changed user-theme@gnome-shell-extensions.gcampax.github.com
Jan 15 14:22:13 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: next check in 60 seconds @ local time 2018-01-15 14:23:13
Jan 15 14:22:13 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: monitor 0 -> 1920 x 1200
Jan 15 14:22:13 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: highest res: 1920 x 1200
Jan 15 14:22:13 schroedinger org.gnome.Shell.desktop[12767]: BingWallpaper extension: detected best resolution 1920x1200
Jan 15 14:22:13 schroedinger gnome-software[13211]: no app for changed BingWallpaper@ineffable-gmail.com
```
Of these, the first run seems fine, since it sets a long timer. The following runs show repeated `WARNING: init() called more than once, ignoring` and `enable() called` and set a 60 second timer.

**Comment by neffo** [comment]
Hmm, my workaround to stop enable() being called twice isn't working. The workaround for init() _is_ though. I have raised a bug with the gnome bugzilla bug tracker [here](https://bugzilla.gnome.org/show_bug.cgi?id=792531).

**Comment by neffo** [comment]
Seem this bug might be related to [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1489554) at the Redhat bugzilla
